# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        default_provider:
             memory:
                 users:
                     ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                     admin: { password: kitten, roles: 'ROLE_ADMIN' }

    firewalls:
        secured_area:
             pattern:    ^/
             anonymous: ~
             form_login:
                 login_path:  login
                 check_path:  login_check
                


        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            
            logout:
                   path: /logout
            
    access_control:
     - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
     - { path: ^/admin, roles: ROLE_ADMIN }
     
    encoders:
         Symfony\Component\Security\Core\User\User: plaintext
    
    
           
           
                  

