# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_users:
              entity: { class: StartBundle\Entity\Uzytkownicy, property: Login }
              
    
     
     
    firewalls:
        secured_area:
             pattern:    ^/
             anonymous: ~
             form_login:
                 login_path:  login
                 check_path:  login_check
                
             logout:
               path: /logout
               target: /                 

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            
           
            
    access_control:
     - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
     - { path: ^/admin, roles: ROLE_ADMIN }
     
    encoders:
           Symfony\Component\Security\Core\User\User: plaintext
    
    
           
           
                  

